### ISSUE TITLE
Status of patch in relation to fire

### ISSUE THREAD

**Issue by kiranaw** [kiranaw/PeatFire#2]
There are 3 possible state of a patch (aboveground) in a given time:
1. not burning AND not burnt (the initial state of all patches)
2. burning AND not burnt (as soon as fire is ignited)
3. not burning AND burnt (as soon as biomass run out)

**Comment by maimron** [comment]
The burnt patches in relation to satellite images should be detected by the images, but still unknown whether the relationship with the biomass, whether the detection represents how many percentage of the biomass is burnt, because the below ground biomass is unknown. But I am sure if the 30 x 30 m2 of earth was burnt, it can be detected.
